### ISSUE TITLE
ATTiny10 is not EOL.

### ISSUE THREAD

**Issue by dpiegdon** [Ladvien/ATtiny10-Projects-and-Libraries#1]
I am glad to inform you that the ATTiny 4/5/9/10 series is not EOL. It seems that Microchip only replaced the ordering codes. If you check the current (REV 8127H, issued 11/16) data sheet pg 12, you can see that the SOT23 (6ST1) package continues with new ordering codes.
You can also search for Microchips EOL notification for ATTiny10, describing the recommended replacement with the exact new ordering codes as in the datasheet.

Also it seems that the new ordering codes describe exactly the same chip. It seems that no silicon revision was issued. Also see pg 203 and 204.

You gave me quite the scare there, as I also like this little uC a lot... :)

**Comment by Ladvien** [comment]
Well, it was still a great excuse to my wife to buy 100 SOT ATtiny10s. :)

That's what I get for not asking Microchip directly if they were going to EOL the SOTs. I combined the last sentence on this [HaD article](http://hackaday.com/2016/01/20/microchip-to-acquire-atmel-for-3-56-billion/) and in Atmel's catalog it stated the SOT was being EOL'ed.  Unfortunately, you'll have to take my word on it, as everything is now directing to Microchip's sales site.

**Comment by dpiegdon** [comment]
thats fine for me, i'm just glad the tiny10 is not EOL and wanted to let you know :)
